export const SAMPLE_DATA = [
  {
    word: "automobile",
    results: [
      {
        definition:
          "a motor vehicle with four wheels; usually propelled by an internal combustion engine",
        partOfSpeech: "noun",
        synonyms: ["auto", "car", "machine", "motorcar"],
        hasCategories: [
          "backseat",
          "rental",
          "tunnel",
          "rider",
          "saleroom",
          "salesroom",
          "grip",
          "chattel",
          "alternator",
          "prang",
          "spark lever",
          "traction",
          "road map",
          "movable",
          "hopped-up",
          "passenger",
          "renting",
          "personal chattel",
          "adhesive friction",
          "showroom",
        ],
        typeOf: ["automotive vehicle", "motor vehicle"],
        hasTypes: [
          "stock car",
          "subcompact",
          "subcompact car",
          "compact",
          "compact car",
          "suv",
          "convertible",
          "taxi",
          "taxicab",
          "coupe",
          "hack",
          "hardtop",
          "tourer",
          "touring car",
          "hatchback",
          "two-seater",
          "used-car",
          "waggon",
          "wagon",
          "heap",
          "cruiser",
          "electric",
          "horseless carriage",
          "hot-rod",
          "hot rod",
          "jalopy",
          "jeep",
          "landrover",
          "limo",
          "limousine",
          "loaner",
          "electric automobile",
          "electric car",
          "estate car",
          "minicar",
          "minivan",
          "model t",
          "bus",
          "pace car",
          "patrol car",
          "cab",
          "phaeton",
          "police car",
          "prowl car",
          "police cruiser",
          "race car",
          "racer",
          "racing car",
          "beach waggon",
          "beach wagon",
          "ambulance",
          "roadster",
          "runabout",
          "gas guzzler",
          "s.u.v.",
          "saloon",
          "secondhand car",
          "sedan",
          "sport car",
          "sport utility",
          "sport utility vehicle",
          "sports car",
          "squad car",
          "stanley steamer",
          "station waggon",
          "station wagon",
        ],
        hasParts: [
          "rear window",
          "accelerator pedal",
          "air bag",
          "anti-sway bar",
          "auto accessory",
          "automobile engine",
          "automobile horn",
          "automobile trunk",
          "bonnet",
          "boot",
          "buffer",
          "bumper",
          "car door",
          "car horn",
          "car mirror",
          "car seat",
          "car window",
          "cowl",
          "cowling",
          "fender",
          "fin",
          "first",
          "first gear",
          "floorboard",
          "gas",
          "gas pedal",
          "gasoline engine",
          "glove compartment",
          "grille",
          "gun",
          "high",
          "high gear",
          "hood",
          "hooter",
          "horn",
          "low",
          "low gear",
          "luggage compartment",
          "motor horn",
          "petrol engine",
          "radiator grille",
          "accelerator",
          "reverse",
          "reverse gear",
          "roof",
          "running board",
          "stabilizer bar",
          "sunroof",
          "sunshine-roof",
          "tail fin",
          "tailfin",
          "third",
          "third gear",
          "throttle",
          "trunk",
          "window",
          "wing",
        ],
        derivation: ["automobilist"],
      },
      {
        definition: "travel in an automobile",
        partOfSpeech: "verb",
        inCategory: ["driving"],
        typeOf: ["locomote", "move", "go", "travel"],
      },
    ],
    syllables: {
      count: 4,
      list: ["au", "to", "mo", "bile"],
    },
    pronunciation: {
      all: ",ɔtəmə'bil",
    },
    frequency: 3.5,
  },
  // {
  //   word: "birthday",
  //   results: [
  //     {
  //       definition: "the date on which a person was born",
  //       partOfSpeech: "noun",
  //       synonyms: ["natal day"],
  //       typeOf: ["date", "day of the month"],
  //     },
  //     {
  //       definition:
  //         "an anniversary of the day on which a person was born (or the celebration of it)",
  //       partOfSpeech: "noun",
  //       typeOf: ["anniversary", "day of remembrance"],
  //     },
  //   ],
  //   syllables: {
  //     count: 2,
  //     list: ["birth", "day"],
  //   },
  //   pronunciation: {
  //     all: "'bɜrθ,deɪ",
  //   },
  //   frequency: 5.07,
  // },
];
